// GENERATED by scripts/gen-sleep-kotlin-test.mjs from scripts/fixtures/sleep-sessions.json.
// Do not edit by hand: change the fixtures, then run
//   node scripts/gen-sleep-kotlin-test.mjs
// The JS side runs the same cases in scripts/sleep-sessions.test.js (#236).
package com.nutritrace.app

import androidx.health.connect.client.records.SleepSessionRecord
import org.junit.Assert.assertEquals
import org.junit.Test
import java.time.ZoneId

class SleepDerivationFixturesTest {
    private fun s(id: String, origin: String, start: Long, end: Long, vararg stages: SleepDerivation.RawStage) =
        SleepDerivation.RawSession(id, origin, start, end, stages.toList())

    private fun st(stage: Int, start: Long, end: Long) = SleepDerivation.RawStage(stage, start, end)

    @Test
    fun stageConstantsAreAndroidX() {
        assertEquals(SleepSessionRecord.STAGE_TYPE_UNKNOWN, SleepDerivation.STAGE_UNKNOWN)
        assertEquals(SleepSessionRecord.STAGE_TYPE_AWAKE, SleepDerivation.STAGE_AWAKE)
        assertEquals(SleepSessionRecord.STAGE_TYPE_SLEEPING, SleepDerivation.STAGE_SLEEPING)
        assertEquals(SleepSessionRecord.STAGE_TYPE_OUT_OF_BED, SleepDerivation.STAGE_OUT_OF_BED)
        assertEquals(SleepSessionRecord.STAGE_TYPE_LIGHT, SleepDerivation.STAGE_LIGHT)
        assertEquals(SleepSessionRecord.STAGE_TYPE_DEEP, SleepDerivation.STAGE_DEEP)
        assertEquals(SleepSessionRecord.STAGE_TYPE_REM, SleepDerivation.STAGE_REM)
        assertEquals(SleepSessionRecord.STAGE_TYPE_AWAKE_IN_BED, SleepDerivation.STAGE_AWAKE_IN_BED)
    }

    @Test
    fun case01_one_session_without_stages_duration_only() {
        val sessions = listOf(
            s("s1", "com.sec.android.app.shealth", 1790107200000L, 1790136000000L)
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Europe/Moscow")) }
        val expected = mapOf<String, Number>("sleep_duration_min" to 480)
        assertEquals("one session without stages: duration only", expected, derive(sessions))
    }

    @Test
    fun case02_236_reporter_s_night_two_samsung_fragments_00_46_05_00_and_0() {
        val sessions = listOf(
            s("frag2", "com.sec.android.app.shealth", 1790131500000L, 1790135580000L, st(4, 1790131500000L, 1790133000000L), st(6, 1790133000000L, 1790134800000L), st(1, 1790134800000L, 1790135580000L)),
            s("frag1", "com.sec.android.app.shealth", 1790113560000L, 1790128800000L, st(4, 1790113560000L, 1790116200000L), st(5, 1790116200000L, 1790119800000L), st(4, 1790119800000L, 1790123400000L), st(6, 1790123400000L, 1790125800000L), st(1, 1790125800000L, 1790125980000L), st(4, 1790125980000L, 1790128800000L))
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Europe/Moscow")) }
        val expected = mapOf<String, Number>("sleep_duration_min" to 322, "sleep_deep_min" to 60, "sleep_light_min" to 176, "sleep_rem_min" to 70, "sleep_wake_min" to 16, "sleep_restlessness_min" to 3, "sleep_interruptions_min" to 0, "sleep_full_awakenings" to 0, "sleep_time_to_fall_asleep_min" to 44, "sleep_sound_sleep_min" to 130)
        assertEquals("#236 reporter's night: two Samsung fragments, 00:46-05:00 and 05:45-06:53, both count", expected, derive(sessions))
        assertEquals("#236 reporter's night: two Samsung fragments, 00:46-05:00 and 05:45-06:53, both count (records in reverse order)", expected, derive(sessions.reversed()))
    }

    @Test
    fun case03_a_second_app_with_no_stages_covering_the_whole_night_does_no() {
        val sessions = listOf(
            s("frag1", "com.sec.android.app.shealth", 1790113560000L, 1790128800000L, st(4, 1790113560000L, 1790116200000L), st(5, 1790116200000L, 1790119800000L), st(4, 1790119800000L, 1790123400000L), st(6, 1790123400000L, 1790125800000L), st(1, 1790125800000L, 1790125980000L), st(4, 1790125980000L, 1790128800000L)),
            s("frag2", "com.sec.android.app.shealth", 1790131500000L, 1790135580000L, st(4, 1790131500000L, 1790133000000L), st(6, 1790133000000L, 1790134800000L), st(1, 1790134800000L, 1790135580000L)),
            s("sched", "com.google.android.apps.fitness", 1790113200000L, 1790136000000L)
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Europe/Moscow")) }
        val expected = mapOf<String, Number>("sleep_duration_min" to 322, "sleep_deep_min" to 60, "sleep_light_min" to 176, "sleep_rem_min" to 70, "sleep_wake_min" to 16, "sleep_restlessness_min" to 3, "sleep_interruptions_min" to 0, "sleep_full_awakenings" to 0, "sleep_time_to_fall_asleep_min" to 44, "sleep_sound_sleep_min" to 130)
        assertEquals("a second app with no stages covering the whole night does not replace the staged fragments", expected, derive(sessions))
        assertEquals("a second app with no stages covering the whole night does not replace the staged fragments (records in reverse order)", expected, derive(sessions.reversed()))
    }

    @Test
    fun case04_the_same_night_written_by_two_staged_apps_is_counted_once_lo() {
        val sessions = listOf(
            s("b1", "com.b.tracker", 1790107200000L, 1790136000000L, st(4, 1790107200000L, 1790136000000L)),
            s("a1", "com.a.tracker", 1790107200000L, 1790136000000L, st(4, 1790107200000L, 1790114400000L), st(5, 1790114400000L, 1790118000000L), st(4, 1790118000000L, 1790132400000L), st(6, 1790132400000L, 1790136000000L))
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Europe/Moscow")) }
        val expected = mapOf<String, Number>("sleep_duration_min" to 480, "sleep_deep_min" to 60, "sleep_light_min" to 360, "sleep_rem_min" to 60, "sleep_wake_min" to 0, "sleep_restlessness_min" to 0, "sleep_interruptions_min" to 0, "sleep_full_awakenings" to 0, "sleep_time_to_fall_asleep_min" to 120, "sleep_sound_sleep_min" to 120)
        assertEquals("the same night written by two staged apps is counted once (lower package name kept)", expected, derive(sessions))
        assertEquals("the same night written by two staged apps is counted once (lower package name kept) (records in reverse order)", expected, derive(sessions.reversed()))
    }

    @Test
    fun case05_one_app_overlapping_itself_by_a_minute_the_minute_is_counted() {
        val sessions = listOf(
            s("p1", "com.sec.android.app.shealth", 1790107200000L, 1790121600000L, st(4, 1790107200000L, 1790121600000L)),
            s("p2", "com.sec.android.app.shealth", 1790121540000L, 1790136000000L, st(4, 1790121540000L, 1790125200000L), st(5, 1790125200000L, 1790136000000L))
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Europe/Moscow")) }
        val expected = mapOf<String, Number>("sleep_duration_min" to 480, "sleep_deep_min" to 180, "sleep_light_min" to 300, "sleep_rem_min" to 0, "sleep_wake_min" to 0, "sleep_restlessness_min" to 0, "sleep_interruptions_min" to 0, "sleep_full_awakenings" to 0, "sleep_time_to_fall_asleep_min" to 300, "sleep_sound_sleep_min" to 180)
        assertEquals("one app overlapping itself by a minute: the minute is counted once", expected, derive(sessions))
        assertEquals("one app overlapping itself by a minute: the minute is counted once (records in reverse order)", expected, derive(sessions.reversed()))
    }

    @Test
    fun case06_an_afternoon_nap_the_same_day_does_not_replace_the_night() {
        val sessions = listOf(
            s("night", "com.sec.android.app.shealth", 1790107200000L, 1790136000000L),
            s("nap", "com.sec.android.app.shealth", 1790161200000L, 1790164800000L)
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Europe/Moscow")) }
        val expected = mapOf<String, Number>("sleep_duration_min" to 480)
        assertEquals("an afternoon nap the same day does not replace the night", expected, derive(sessions))
        assertEquals("an afternoon nap the same day does not replace the night (records in reverse order)", expected, derive(sessions.reversed()))
    }

    @Test
    fun case07_a_fragment_that_ended_before_midnight_still_belongs_to_the_n() {
        val sessions = listOf(
            s("eve", "com.sec.android.app.shealth", 1790103600000L, 1790109000000L),
            s("rest", "com.sec.android.app.shealth", 1790111700000L, 1790134200000L)
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Europe/Moscow")) }
        val expected = mapOf<String, Number>("sleep_duration_min" to 465)
        assertEquals("a fragment that ended before midnight still belongs to the night", expected, derive(sessions))
        assertEquals("a fragment that ended before midnight still belongs to the night (records in reverse order)", expected, derive(sessions.reversed()))
    }

    @Test
    fun case08_a_night_that_ended_yesterday_is_not_today_s_sleep() {
        val sessions = listOf(
            s("old", "com.sec.android.app.shealth", 1790020800000L, 1790049600000L)
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Europe/Moscow")) }
        val expected = emptyMap<String, Number>()
        assertEquals("a night that ended yesterday is not today's sleep", expected, derive(sessions))
    }

    @Test
    fun case09_a_gap_of_3_hours_splits_the_night_equal_halves_keep_the_late() {
        val sessions = listOf(
            s("h1", "com.sec.android.app.shealth", 1790103600000L, 1790114400000L),
            s("h2", "com.sec.android.app.shealth", 1790125200000L, 1790136000000L)
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Europe/Moscow")) }
        val expected = mapOf<String, Number>("sleep_duration_min" to 180)
        assertEquals("a gap of 3 hours splits the night; equal halves keep the later one", expected, derive(sessions))
        assertEquals("a gap of 3 hours splits the night; equal halves keep the later one (records in reverse order)", expected, derive(sessions.reversed()))
    }

    @Test
    fun case10_a_gap_just_under_3_hours_is_one_night() {
        val sessions = listOf(
            s("h1", "com.sec.android.app.shealth", 1790103600000L, 1790114400000L),
            s("h2", "com.sec.android.app.shealth", 1790125140000L, 1790135940000L)
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Europe/Moscow")) }
        val expected = mapOf<String, Number>("sleep_duration_min" to 360)
        assertEquals("a gap just under 3 hours is one night", expected, derive(sessions))
        assertEquals("a gap just under 3 hours is one night (records in reverse order)", expected, derive(sessions.reversed()))
    }

    @Test
    fun case11_awake_in_bed_counts_as_awake_out_of_bed_sleeping_and_unknown() {
        val sessions = listOf(
            s("v", "com.sec.android.app.shealth", 1790107200000L, 1790136000000L, st(7, 1790107200000L, 1790107680000L), st(4, 1790107680000L, 1790114400000L), st(3, 1790114400000L, 1790115000000L), st(2, 1790115000000L, 1790118000000L), st(5, 1790118000000L, 1790121600000L), st(0, 1790121600000L, 1790121900000L), st(6, 1790121900000L, 1790136000000L))
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Europe/Moscow")) }
        val expected = mapOf<String, Number>("sleep_duration_min" to 480, "sleep_deep_min" to 60, "sleep_light_min" to 112, "sleep_rem_min" to 235, "sleep_wake_min" to 8, "sleep_restlessness_min" to 0, "sleep_interruptions_min" to 0, "sleep_full_awakenings" to 0, "sleep_time_to_fall_asleep_min" to 180, "sleep_sound_sleep_min" to 295)
        assertEquals("AWAKE_IN_BED counts as awake; OUT_OF_BED, SLEEPING and UNKNOWN count toward no stage", expected, derive(sessions))
    }

    @Test
    fun case12_interruptions_restlessness_and_the_settling_in_and_wake_up_b() {
        val sessions = listOf(
            s("q", "com.sec.android.app.shealth", 1790107200000L, 1790136000000L, st(4, 1790107200000L, 1790110800000L), st(5, 1790110800000L, 1790114400000L), st(1, 1790114400000L, 1790115120000L), st(4, 1790115120000L, 1790116800000L), st(1, 1790116800000L, 1790117220000L), st(4, 1790117220000L, 1790118000000L), st(1, 1790118000000L, 1790118180000L), st(6, 1790118180000L, 1790121600000L), st(4, 1790121600000L, 1790121840000L), st(5, 1790121840000L, 1790135400000L), st(1, 1790135400000L, 1790136000000L))
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Europe/Moscow")) }
        val expected = mapOf<String, Number>("sleep_duration_min" to 480, "sleep_deep_min" to 286, "sleep_light_min" to 105, "sleep_rem_min" to 57, "sleep_wake_min" to 32, "sleep_restlessness_min" to 3, "sleep_interruptions_min" to 7, "sleep_full_awakenings" to 1, "sleep_time_to_fall_asleep_min" to 60, "sleep_sound_sleep_min" to 347)
        assertEquals("interruptions, restlessness and the settling-in and wake-up blocks follow the Google Health walk", expected, derive(sessions))
    }

    @Test
    fun case13_no_sessions() {
        val sessions = emptyList<SleepDerivation.RawSession>()
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Europe/Moscow")) }
        val expected = emptyMap<String, Number>()
        assertEquals("no sessions", expected, derive(sessions))
    }

    @Test
    fun case14_a_stage_running_past_its_session_is_clipped_to_it() {
        val sessions = listOf(
            s("c", "com.sec.android.app.shealth", 1790107200000L, 1790136000000L, st(4, 1790106600000L, 1790136600000L))
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Europe/Moscow")) }
        val expected = mapOf<String, Number>("sleep_duration_min" to 480, "sleep_deep_min" to 0, "sleep_light_min" to 480, "sleep_rem_min" to 0, "sleep_wake_min" to 0, "sleep_restlessness_min" to 0, "sleep_interruptions_min" to 0, "sleep_full_awakenings" to 0)
        assertEquals("a stage running past its session is clipped to it", expected, derive(sessions))
    }

    @Test
    fun case15_a_session_that_ends_before_it_starts_is_ignored() {
        val sessions = listOf(
            s("bad", "com.sec.android.app.shealth", 1790136000000L, 1790132400000L),
            s("good", "com.sec.android.app.shealth", 1790107200000L, 1790136000000L)
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Europe/Moscow")) }
        val expected = mapOf<String, Number>("sleep_duration_min" to 480)
        assertEquals("a session that ends before it starts is ignored", expected, derive(sessions))
        assertEquals("a session that ends before it starts is ignored (records in reverse order)", expected, derive(sessions.reversed()))
    }

    @Test
    fun case16_the_night_the_clocks_go_back_is_9_hours_not_8_america_new_yo() {
        val sessions = listOf(
            s("dst", "com.sec.android.app.shealth", 1793502000000L, 1793534400000L)
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-11-01", ZoneId.of("America/New_York")) }
        val expected = mapOf<String, Number>("sleep_duration_min" to 540)
        assertEquals("the night the clocks go back is 9 hours, not 8 (America/New_York)", expected, derive(sessions))
    }

    @Test
    fun case17_the_local_wake_up_date_decides_not_the_utc_one_asia_tokyo() {
        val sessions = listOf(
            s("tk", "com.sec.android.app.shealth", 1790085600000L, 1790114400000L)
        )
        val derive = { list: List<SleepDerivation.RawSession> -> SleepDerivation.derive(list, "2026-09-23", ZoneId.of("Asia/Tokyo")) }
        val expected = mapOf<String, Number>("sleep_duration_min" to 480)
        assertEquals("the local wake-up date decides, not the UTC one (Asia/Tokyo)", expected, derive(sessions))
    }
}
